/*

 BACKGROUNDTILEMAPNIGHT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundTileMapNightWidth 32
#define BackgroundTileMapNightHeight 18
#define BackgroundTileMapNightBank 0

extern unsigned char BackgroundTileMapNight[];

/* End of BACKGROUNDTILEMAPNIGHT.H */
