#ifndef TILES_H
#define TILES_H

// -- Dino Tile Index Definition

#define FIRST_DINO_TILE_INDEX 1
#define COUNT_DINO_TILE 18

#define TILE_DINO_HEAD_1 0 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_HEAD_2 1 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_BODY_1 2 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_BODY_2 3 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_BODY_3 4 + FIRST_DINO_TILE_INDEX

// Different legs for the walking animation
#define TILE_DINO_FOOT_LEFT_FLOOR 5 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_FOOT_LEFT_UP 7 + FIRST_DINO_TILE_INDEX

#define TILE_DINO_FOOT_RIGHT_FLOOR 6 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_FOOT_RIGHT_UP 8 + FIRST_DINO_TILE_INDEX

// Head Tiles for the Game Over 
#define TILE_DINO_HEAD_1_GAME_OVER 9 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_HEAD_2_GAME_OVER 10 + FIRST_DINO_TILE_INDEX

// When Dino is Down
#define TILE_DINO_DOWN_BODY_1 11 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_HEAD_1 12 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_HEAD_2 13 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_HEAD_3 15 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_HEAD_4 16 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_FOOT_RIGHT_FLOOR 14 + FIRST_DINO_TILE_INDEX
#define TILE_DINO_DOWN_FOOT_RIGHT_UP 17 + FIRST_DINO_TILE_INDEX

#define LAST_DINO_TILE_INDEX TILE_DINO_DOWN_FOOT_RIGHT_UP


// -- Cactus Tile Index Definition

#define FIRST_CACTUS_TILE_INDEX 1 + LAST_DINO_TILE_INDEX

#define COUNT_CACTUS_TILE 9

#define TILE_BIG_CACTUS_0_0 0 + FIRST_CACTUS_TILE_INDEX
#define TILE_BIG_CACTUS_0_1 1 + FIRST_CACTUS_TILE_INDEX
#define TILE_BIG_CACTUS_1_0 2 + FIRST_CACTUS_TILE_INDEX
#define TILE_BIG_CACTUS_1_1 3 + FIRST_CACTUS_TILE_INDEX
#define TILE_BIG_CACTUS_2_1 4 + FIRST_CACTUS_TILE_INDEX
#define TILE_BIG_CACTUS_2_2 5 + FIRST_CACTUS_TILE_INDEX

#define TILE_SMALL_CACTUS_0_0 6 + FIRST_CACTUS_TILE_INDEX
#define TILE_SMALL_CACTUS_0_1 7 + FIRST_CACTUS_TILE_INDEX
#define TILE_SMALL_CACTUS_1_1 8 + FIRST_CACTUS_TILE_INDEX

#define LAST_CACTUS_TILE_INDEX TILE_SMALL_CACTUS_1_1


// -- Bird Tile Index Definition

#define FIRST_BIRD_TILE_INDEX 1 + LAST_CACTUS_TILE_INDEX

#define COUNT_BIRD_TILE 6

// Tile Position on Memory for each part of the Bird Sprite
#define TILE_BIRD_HEAD 0 + FIRST_BIRD_TILE_INDEX
#define TILE_BIRD_BODY_WING_DOWN 1 + FIRST_BIRD_TILE_INDEX
#define TILE_BIRD_TAIL 2 + FIRST_BIRD_TILE_INDEX
#define TILE_BIRD_WING_DOWN 3 + FIRST_BIRD_TILE_INDEX
#define TILE_BIRD_WING_UP 4 + FIRST_BIRD_TILE_INDEX
#define TILE_BIRD_BODY_WING_UP 5 + FIRST_BIRD_TILE_INDEX

#define LAST_BIRD_TILE_INDEX TILE_BIRD_WING_UP


// -- Characters and Numbers Tile Index Definition

#define CHARACTER_TILE_START_INDEX 50

#define COUNT_CHARACTER_TILE 22

#define P_TILE 0 + CHARACTER_TILE_START_INDEX
#define R_TILE 1 + CHARACTER_TILE_START_INDEX
#define E_TILE 2 + CHARACTER_TILE_START_INDEX
#define S_TILE 3 + CHARACTER_TILE_START_INDEX
#define A_TILE 4 + CHARACTER_TILE_START_INDEX
#define N_TILE 5 + CHARACTER_TILE_START_INDEX
#define Y_TILE 6 + CHARACTER_TILE_START_INDEX
#define K_TILE 7 + CHARACTER_TILE_START_INDEX
#define G_TILE 8 + CHARACTER_TILE_START_INDEX
#define M_TILE 9 + CHARACTER_TILE_START_INDEX
#define O_TILE 10 + CHARACTER_TILE_START_INDEX
#define V_TILE 11 + CHARACTER_TILE_START_INDEX

#define NUMBER_CHARACTERS_OFFSET 12 + CHARACTER_TILE_START_INDEX


#endif
